# Generated by Django 3.2.5 on 2021-07-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.IntegerField(default=False)),
                ('budget', models.IntegerField()),
                ('preferred_restuarnt', models.TextField()),
                ('preferred_cusine', models.TextField()),
                ('upload_mess_menu', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
    ]
