# Generated by Django 3.2.5 on 2021-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210730_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_mess_menu', models.FileField(upload_to='uploads/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='upload_mess_menu',
        ),
    ]
