# Generated by Django 3.2.5 on 2021-07-31 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210730_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='preferred_cusine',
            new_name='preferred_cuisine',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='preferred_restuarnt',
            new_name='preferred_restuarant',
        ),
    ]
