# Generated by Django 3.2.5 on 2021-07-31 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210731_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='preferred_cuisine',
            new_name='preferred_cuisines',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='preferred_restuarant',
            new_name='preferred_restaurant',
        ),
    ]
