# Generated by Django 3.2.5 on 2021-07-31 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210731_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='preferred_restaurant',
            new_name='preferred_restaurants',
        ),
    ]
