# Generated by Django 3.2.5 on 2021-08-02 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_mess_menu',
        ),
        migrations.AddField(
            model_name='document',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='food_item_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
