# Generated by Django 3.2.5 on 2021-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_document_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='budget',
            new_name='budget_spent',
        ),
        migrations.AddField(
            model_name='student',
            name='budget_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
