# Generated by Django 3.2.5 on 2021-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210804_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='budget_spent',
            field=models.IntegerField(default=0),
        ),
    ]
