# Generated by Django 3.2.5 on 2021-08-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210826_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='DOB',
        ),
        migrations.AddField(
            model_name='student',
            name='DOB_date',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='DOB_month',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='DOB_year',
            field=models.IntegerField(default=1999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='DOB_date',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='DOB_month',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='DOB_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
