# Generated by Django 3.2.5 on 2021-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210826_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='Account_Holder',
            field=models.CharField(default='xyz', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='Account_Holder',
            field=models.CharField(default='abcd', max_length=300),
            preserve_default=False,
        ),
    ]
