# Generated by Django 3.2.5 on 2021-08-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='ser',
            new_name='user',
        ),
    ]
