# Generated by Django 3.2.5 on 2021-08-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Account_Bal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Account_Bal',
            field=models.IntegerField(default=0),
        ),
    ]
