# Generated by Django 3.2.5 on 2021-08-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_ser_vendor_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Menu',
        ),
    ]
