# Generated by Django 3.2.5 on 2021-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_document_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='latitude',
            field=models.FloatField(default=123.123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='longitute',
            field=models.FloatField(default=345.345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.FloatField(default=2344.231),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitute',
            field=models.FloatField(default=3234.23),
            preserve_default=False,
        ),
    ]
