# Generated by Django 3.2.5 on 2021-08-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210809_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
