# Generated by Django 3.2.5 on 2021-08-10 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_rename_longitute_vendor_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AMOUNT', models.FloatField()),
                ('DATE_TIME', models.DateTimeField(auto_now=True)),
                ('FROM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FROM', to=settings.AUTH_USER_MODEL)),
                ('TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
