# Generated by Django 3.2.5 on 2021-08-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_first_name_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='first_name',
        ),
    ]
