# Generated by Django 3.2.5 on 2021-08-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_name_student_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
    ]
