# Generated by Django 3.2.5 on 2021-08-26 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_rename_first_name_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcations',
            name='AMOUNT',
        ),
        migrations.RemoveField(
            model_name='transcations',
            name='DATE_TIME',
        ),
        migrations.RemoveField(
            model_name='transcations',
            name='FROM',
        ),
        migrations.RemoveField(
            model_name='transcations',
            name='TO',
        ),
        migrations.AddField(
            model_name='student',
            name='Account_ID',
            field=models.CharField(default='bcdefgh', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcations',
            name='amount',
            field=models.FloatField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcations',
            name='reciever',
            field=models.ForeignKey(default='ka', on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcations',
            name='sender',
            field=models.ForeignKey(default='kp', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transcations',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Account_ID',
            field=models.CharField(default='asbcasjndf', max_length=300),
            preserve_default=False,
        ),
    ]
